### ISSUE TITLE
installation problem on "pip install -e submodules/depth-diff-gaussian-rasterization"

### ISSUE THREAD

**Issue by navalguijo** [hustvl/4DGaussians#10]
I already installed cudatoolkit=11.6 and pytorch=1.13.1
Can you please help me to make it work?

(Gaussians4D) Y:\AI\4DGaussians>pip install -e submodules/depth-diff-gaussian-rasterization
Obtaining file:///Y:/AI/4DGaussians/submodules/depth-diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Installing collected packages: diff-gaussian-rasterization
  Running setup.py develop for diff-gaussian-rasterization
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [58 lines of output]
        running develop
        running egg_info
        writing diff_gaussian_rasterization.egg-info\PKG-INFO
        writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
        writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
        reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
        adding license file 'LICENSE.md'
        writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
        running build_ext
        No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
        Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          EasyInstallDeprecationWarning,
        Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          setuptools.SetuptoolsDeprecationWarning,
        Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
          warnings.warn(msg.format('we could not find ninja.'))
        Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] El sistema no puede encontrar el archivo especificado
          warnings.warn(f'Error checking compiler version for {compiler}: {error}')
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "Y:\AI\4DGaussians\submodules\depth-diff-gaussian-rasterization\setup.py", line 32, in <module>
            'build_ext': BuildExtension
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
            return run_commands(dist)
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
            dist.run_commands()
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
            super().run_command(command)
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
            cmd_obj.run()
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 34, in run
            self.install_for_development()
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
            self.run_command('build_ext')
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
            super().run_command(command)
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
            cmd_obj.run()
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
            _build_ext.run(self)
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
            self.build_extensions()
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
            _check_cuda_version(compiler_name, compiler_version)
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
            torch_cuda_version = packaging.version.parse(torch.version.cuda)
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
            return Version(version)
          File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
            match = self._regex.search(version)
        TypeError: expected string or bytes-like object
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [58 lines of output]
    running develop
    running egg_info
    writing diff_gaussian_rasterization.egg-info\PKG-INFO
    writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
    writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
    reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
    adding license file 'LICENSE.md'
    writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
    running build_ext
    No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
    Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] El sistema no puede encontrar el archivo especificado
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "Y:\AI\4DGaussians\submodules\depth-diff-gaussian-rasterization\setup.py", line 32, in <module>
        'build_ext': BuildExtension
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
        return run_commands(dist)
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
        dist.run_commands()
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
        self.build_extensions()
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
        _check_cuda_version(compiler_name, compiler_version)
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
        torch_cuda_version = packaging.version.parse(torch.version.cuda)
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
        return Version(version)
      File "Y:\AI\Anaconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by guanjunwu** [comment]
emm, the log said `No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'`
 maybe the path of cuda are not confirmed?

**Comment by henrypearce4D** [comment]
From the log, it looks like you are using cuda v11.7, the requirements.txt will install packages that are not compatible with cuda v11.7 and python 3.7

First check your installed cuda version typing in a command prompt;
`nvcc --version`

If it says at the bottom;
`Build cuda_11.7`

Then run these commands, make sure you have activated your conda env first;
`conda activate Gaussians4D`
`pip uninstall torch torchvision torchaudio`

Then;

`pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==1.3.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117`

After that;

`pip install -e submodules/depth-diff-gaussian-rasterization`
`pip install -e submodules/simple-knn`

See how that goes, hopefully I found the right versions for you.

**Comment by navalguijo** [comment]
> 
> `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==1.3.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117`
> 
this gives me this error:

ERROR: Could not find a version that satisfies the requirement torchaudio==1.3.1+cu117 (from versions: 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.0+cu117, 0.13.1, 0.13.1+cu117)
ERROR: No matching distribution found for torchaudio==1.3.1+cu117

**Comment by navalguijo** [comment]
> emm, the log said `No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'` maybe the path of cuda is not confirmed?
I had this in my system PATH
<img width="464" alt="image" src="https://github.com/hustvl/4DGaussians/assets/5795959/55529a7a-0288-43d9-a402-77bc0d1c2ed1">

**Comment by navalguijo** [comment]
> The version number was incorrect, 1.3.1 should be 0.13.1, try this;
> 
> `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu11`

Still getting error

(Gaussians4D) Y:\AI\4DGaussians>pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu11
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu11
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu117 (from versions: 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for torch==1.13.1+cu117

would it be easier if I install another CUDA version?

**Comment by henrypearce4D** [comment]
Should be up and running soon so stick with v11.7

The link I sent was missing the full version at the end - cu117, try with this;

`pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117`

The file is there so should be picked up
https://download.pytorch.org/whl/torch/
![image](https://github.com/hustvl/4DGaussians/assets/106480554/a9ad4385-b8d6-430f-b942-6cfb0d59adef)

**Comment by pavelf200205** [comment]
I have successfully built it with CUDA 11.8, python 3.11.4 and torch 2.0.1

**Comment by navalguijo** [comment]
> Should be up and running soon so stick with v11.7
> 
> The link I sent was missing the full version at the end - cu117, try with this;
> 
> `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117`
> 
> The file is there so should be picked up https://download.pytorch.org/whl/torch/ ![image](https://user-images.githubusercontent.com/106480554/275833587-a9ad4385-b8d6-430f-b942-6cfb0d59adef.png)

aparently this one worked! Thanx a lot @henrypearce4D

**Comment by LemonZhong** [comment]
CUDA Version:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

I have built with,

pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

However, there are some problems, how can I solve it

![image](https://github.com/hustvl/4DGaussians/assets/89432570/ab4fc2ce-ae75-4edd-8ac9-1efd1c3feca2)

**Comment by BenjaminJaume** [comment]
> From the log, it looks like you are using cuda v11.7, the requirements.txt will install packages that are not compatible with cuda v11.7 and python 3.7
> 
> First check your installed cuda version typing in a command prompt; `nvcc --version`
> 
> If it says at the bottom; `Build cuda_11.7`
> 
> Then run these commands, make sure you have activated your conda env first; `conda activate Gaussians4D` `pip uninstall torch torchvision torchaudio`
> 
> Then;
> 
> `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117`
> 
> After that;
> 
> `pip install -e submodules/depth-diff-gaussian-rasterization` `pip install -e submodules/simple-knn`
> 
> See how that goes, hopefully I found the right versions for you.

That solved it for me, thank you!
