### ISSUE TITLE
Error installing submodules

### ISSUE THREAD

**Issue by BenjaminJaume** [hustvl/4DGaussians#135]
Hi, thank you for your great work!

After following the first 3DGS video tutorial, then your installation guidelines, I am running into some issues while trying to install/build the submodules `depth-diff-gaussian-rasterization` and `simple-knn`. I am running `pip install -e submodules/depth-diff-gaussian-rasterization` and here's the error I am getting:

```
Obtaining file:///C:/projects/4DGaussians/submodules/depth-diff-gaussian-rasterization
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\projects\4DGaussians\submodules\depth-diff-gaussian-rasterization\setup.py", line 13, in <module>
          from torch.utils.cpp_extension import CUDAExtension, BuildExtension
        File "C:\Users\Presence\.conda\envs\Gaussians4D\lib\site-packages\torch\__init__.py", line 676, in <module>
          from .storage import _StorageBase, TypedStorage, _LegacyStorage, UntypedStorage
        File "C:\Users\Presence\.conda\envs\Gaussians4D\lib\site-packages\torch\storage.py", line 11, in <module>
          import numpy as np
        File "C:\Users\Presence\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 148, in <module>
          from . import _distributor_init
        File "C:\Users\Presence\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
          WinDLL(os.path.abspath(filename))
        File "C:\Users\Presence\.conda\envs\Gaussians4D\lib\ctypes\__init__.py", line 356, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: [WinError 193] %1 is not a valid Win32 application
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(Gaussians4D)
```

My PC is a Dell XPS 15 9560, with Windows 10 x64 machine, 32GB of Ram, and an NVIDIA GeForce GTX 1050 4096MB.

Thank you for any help.

**Comment by guanjunwu** [comment]
Hi, did you success to run the valinna 3DGS's training pipeline?
I dont think the install error will happen if 3D-GS can be trained on your environment.
Besides, do you still have problem with the real time viewer??

**Comment by BenjaminJaume** [comment]
Thank you for your answer.

Yes, I was able to run the 3DGS trainline pipeline. And I did not have problem using the real time viewer.

**Comment by guanjunwu** [comment]
Emmmm it actually beyond my skills.
You can go to the original [webpage ](https://github.com/ingra14m/depth-diff-gaussian-rasterization)to ask the author, maybe he can help you ...
sorry for that :(

**Comment by BenjaminJaume** [comment]
No problems. Thank you for taking the time to answer!

**Comment by WHUEugene** [comment]
你解决了吗？我遇到了和你同样的问题
