### ISSUE TITLE
No module named 'tkinter'

### ISSUE THREAD

**Issue by GiadaFerreri** [hustvl/4DGaussians#136]
I'm trying this github but I'm facing some issues. In fact, when I try to run "python train.py ..." for training my own dataset this following message appears: 
![Tkinter](https://github.com/hustvl/4DGaussians/assets/115036543/1c325a11-2621-481c-92b8-0eb40721684b)

I've already tried to install this module in many different ways but nothing seems to work. Somebody can help me, please?

**Comment by BenjaminJaume** [comment]
Hi, it looks like you did not activate the conda environement. Did you run `conda activate Gaussians4D` ?

**Comment by GiadaFerreri** [comment]
> Hi, it looks like you did not activate the conda environement. Did you run `conda activate Gaussians4D` ?

Hi, thank you for your answer. I tried to activate the conda environment but I got this message when I try to run 'pip install -e submodules/depth-diff-gaussian-rasterization': 
`Preparing metadata (setup.py) ... done
Installing collected packages: diff-gaussian-rasterization
  Running setup.py develop for diff-gaussian-rasterization
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [58 lines of output]
        running develop
        running egg_info
        writing diff_gaussian_rasterization.egg-info\PKG-INFO
        writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
        writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
        reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
        adding license file 'LICENSE.md'
        writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
        running build_ext
        No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
        C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          EasyInstallDeprecationWarning,
        C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          setuptools.SetuptoolsDeprecationWarning,
        C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
          warnings.warn(msg.format('we could not find ninja.'))
        C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] Impossibile trovare il file specificato
          warnings.warn(f'Error checking compiler version for {compiler}: {error}')
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "C:\Users\LabXR_2\Docker\workspace\4DGaussians\submodules\depth-diff-gaussian-rasterization\setup.py", line 32, in <module>
            'build_ext': BuildExtension
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_init_.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
            return run_commands(dist)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
            dist.run_commands()
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
            super().run_command(command)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
            cmd_obj.run()
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 34, in run
            self.install_for_development()
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
            self.run_command('build_ext')
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
            super().run_command(command)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
            cmd_obj.run()
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
            _build_ext.run(self)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
            self.build_extensions()
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
            _check_cuda_version(compiler_name, compiler_version)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
            torch_cuda_version = packaging.version.parse(torch.version.cuda)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
            return Version(version)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\vendor\packaging\version.py", line 264, in __init_
            match = self._regex.search(version)
        TypeError: expected string or bytes-like object
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [58 lines of output]
    running develop
    running egg_info
    writing diff_gaussian_rasterization.egg-info\PKG-INFO
    writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
    writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
    reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
    adding license file 'LICENSE.md'
    writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
    running build_ext
    No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
    C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] Impossibile trovare il file specificato
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "C:\Users\LabXR_2\Docker\workspace\4DGaussians\submodules\depth-diff-gaussian-rasterization\setup.py", line 32, in <module>
        'build_ext': BuildExtension
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_init_.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
        return run_commands(dist)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
        dist.run_commands()
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
        self.build_extensions()
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
        _check_cuda_version(compiler_name, compiler_version)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
        torch_cuda_version = packaging.version.parse(torch.version.cuda)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
        return Version(version)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\vendor\packaging\version.py", line 264, in __init_
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by GiadaFerreri** [comment]
> Hi, it looks like you did not activate the conda environement. Did you run `conda activate Gaussians4D` ?

Hi, thank you for your answer. I tried to activate the conda environment but I got this message when I try to run 'pip install -e submodules/depth-diff-gaussian-rasterization':
`Preparing metadata (setup.py) ... done
Installing collected packages: diff-gaussian-rasterization
  Running setup.py develop for diff-gaussian-rasterization
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [58 lines of output]
        running develop
        running egg_info
        writing diff_gaussian_rasterization.egg-info\PKG-INFO
        writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
        writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
        reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
        adding license file 'LICENSE.md'
        writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
        running build_ext
        No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
        C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          EasyInstallDeprecationWarning,
        C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          setuptools.SetuptoolsDeprecationWarning,
        C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
          warnings.warn(msg.format('we could not find ninja.'))
        C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] Impossibile trovare il file specificato
          warnings.warn(f'Error checking compiler version for {compiler}: {error}')
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "C:\Users\LabXR_2\Docker\workspace\4DGaussians\submodules\depth-diff-gaussian-rasterization\setup.py", line 32, in <module>
            'build_ext': BuildExtension
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_init_.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
            return run_commands(dist)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
            dist.run_commands()
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
            super().run_command(command)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
            cmd_obj.run()
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 34, in run
            self.install_for_development()
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
            self.run_command('build_ext')
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
            super().run_command(command)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
            cmd_obj.run()
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
            _build_ext.run(self)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
            self.build_extensions()
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
            _check_cuda_version(compiler_name, compiler_version)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
            torch_cuda_version = packaging.version.parse(torch.version.cuda)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
            return Version(version)
          File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\vendor\packaging\version.py", line 264, in __init_
            match = self._regex.search(version)
        TypeError: expected string or bytes-like object
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [58 lines of output]
    running develop
    running egg_info
    writing diff_gaussian_rasterization.egg-info\PKG-INFO
    writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
    writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
    reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
    adding license file 'LICENSE.md'
    writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
    running build_ext
    No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
    C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] Impossibile trovare il file specificato
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "C:\Users\LabXR_2\Docker\workspace\4DGaussians\submodules\depth-diff-gaussian-rasterization\setup.py", line 32, in <module>
        'build_ext': BuildExtension
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_init_.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
        return run_commands(dist)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
        dist.run_commands()
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
        self.build_extensions()
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
        _check_cuda_version(compiler_name, compiler_version)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
        torch_cuda_version = packaging.version.parse(torch.version.cuda)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
        return Version(version)
      File "C:\Users\LabXR_2\miniconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\vendor\packaging\version.py", line 264, in __init_
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by guanjunwu** [comment]
Hi, can you show your CUDA version, pytorch version?
besides, log said Ninja didn't installed. Maybe you can install ninja at first?

**Comment by GiadaFerreri** [comment]
> Hi, can you show your CUDA version, pytorch version? besides, log said Ninja didn't installed. Maybe you can install ninja at first?

Hi, I installed ninja and the problem was solved. Thank you for your support.
