### ISSUE TITLE
 python setup.py develop did not run successfully.

### ISSUE THREAD

**Issue by CBDXS1** [hustvl/4DGaussians#154]

**Comment by guanjunwu** [comment]
Hi, which setup.py?

**Comment by CBDXS1** [comment]
你好
我运行这个pip install -e submodules/depth-diff-gaussian-rasterization的报错
Obtaining file:///E:/gaosi/4DGaussians/submodules/depth-diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Installing collected packages: diff-gaussian-rasterization
  Running setup.py develop for diff-gaussian-rasterization
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [58 lines of output]
        running develop
        running egg_info
        writing diff_gaussian_rasterization.egg-info\PKG-INFO
        writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
        writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
        reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
        adding license file 'LICENSE.md'
        writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
        running build_ext
        No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
        E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          EasyInstallDeprecationWarning,
        E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          setuptools.SetuptoolsDeprecationWarning,
        E:\ancodn\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
          warnings.warn(msg.format('we could not find ninja.'))
        E:\ancodn\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: 'cp1' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
          warnings.warn(f'Error checking compiler version for {compiler}: {error}')
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "E:\gaosi\4DGaussians\submodules\depth-diff-gaussian-rasterization\setup.py", line 32, in <module>
            'build_ext': BuildExtension
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
            return run_commands(dist)
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
            dist.run_commands()
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
            super().run_command(command)
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
            cmd_obj.run()
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 34, in run
            self.install_for_development()
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
            self.run_command('build_ext')
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
            super().run_command(command)
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
            cmd_obj.run()
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
            _build_ext.run(self)
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
            self.build_extensions()
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
            _check_cuda_version(compiler_name, compiler_version)
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
            torch_cuda_version = packaging.version.parse(torch.version.cuda)
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
            return Version(version)
          File "E:\ancodn\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
            match = self._regex.search(version)
        TypeError: expected string or bytes-like object
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [58 lines of output]
    running develop
    running egg_info
    writing diff_gaussian_rasterization.egg-info\PKG-INFO
    writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
    writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
    reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
    adding license file 'LICENSE.md'
    writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
    running build_ext
    No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
    E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    E:\ancodn\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    E:\ancodn\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: 'cp1' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "E:\gaosi\4DGaussians\submodules\depth-diff-gaussian-rasterization\setup.py", line 32, in <module>
        'build_ext': BuildExtension
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
        return run_commands(dist)
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
        dist.run_commands()
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
        self.build_extensions()
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
        _check_cuda_version(compiler_name, compiler_version)
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
        torch_cuda_version = packaging.version.parse(torch.version.cuda)
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 49, in parse
        return Version(version)
      File "E:\ancodn\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
我是一个萌新，找了一天没找到问题所在。

**Comment by CBDXS1** [comment]
> 你好，哪个 setup.py？

求求了哥，计算机没脑子，太熬人了

**Comment by guanjunwu** [comment]
it seems like your cuda version=11.8, what is your torch's version?

**Comment by CBDXS1** [comment]
> 好像你的 cuda 版本=11.8，你的 torch 的版本是什么？ 它应该与你的 cuda 版本相对应。

OK，我回去看看，并且试一试，十分感谢

**Comment by CBDXS1** [comment]
> 根据`No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'`行号，这似乎是您环境中的 CUDA 安装错误。检查 cuda 安装和路径声明是正确的。
> 
> 干杯

这个方法我试过了，好像不是这个问题，但也很感谢你
