### ISSUE TITLE
A problem on training 

### ISSUE THREAD

**Issue by mayBeYan** [hustvl/4DGaussians#161]
PS D:\Project_3DGS\4DGaussians> python train.py -s data/multipleview/input                                                                                      
2024-07-11 18:25:33.076885: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-11 18:25:33.474622: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Optimizing 
Output folder: ./output/ [11/07 18:25:34]
feature_dim: 128 [11/07 18:25:34]
Traceback (most recent call last):
  File "D:\Project_3DGS\4DGaussians\train.py", line 429, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "D:\Project_3DGS\4DGaussians\train.py", line 303, in training
    scene = Scene(dataset, gaussians, load_coarse=None)
  File "D:\Project_3DGS\4DGaussians\scene\__init__.py", line 62, in __init__
    scene_info = sceneLoadTypeCallbacks["MultipleView"](args.source_path)
  File "D:\Project_3DGS\4DGaussians\scene\dataset_readers.py", line 603, in readMultipleViewinfos
    train_cam_infos = multipleview_dataset(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics, cam_folder=datadir,split="train")
  File "D:\Project_3DGS\4DGaussians\scene\multipleview_dataset.py", line 20, in __init__
    self.focal = [cam_intrinsics[1].params[0], cam_intrinsics[1].params[0]]
KeyError: 1

Excuse me ,
When training ,i got the error information above . I think it is the problem about the cam input ,but i could not find the reason,paticularly the meaning of "KeyError: 1".
My input is like this ,could you help me solve this problem
![791a96658fc44955424a91a9e3154e4](https://github.com/hustvl/4DGaussians/assets/137168938/a3d01161-66c1-47fa-a975-099f82313b93)

**Comment by guanjunwu** [comment]
e, why your multiple view dataset only have one camera?

**Comment by crazyzyz** [comment]
Hi, I also encountered this problem. Have you solved it? How did you solve it

**Comment by chicleee** [comment]
Has anyone solved this problem yet ?
