### ISSUE TITLE
No such file or directory:cam103

### ISSUE THREAD

**Issue by mayBeYan** [hustvl/4DGaussians#162]
Error information
 PS D:\Project_3DGS\4DGaussians> python train.py -s data/multipleview/inputimage --port 6017 --expname "multipleview/inputimage" --configs arguments/multipleview/inputimage.py 
2024-07-12 15:54:08.078370: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-12 15:54:08.493721: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Optimizing 
Output folder: ./output/multipleview/inputimage [12/07 15:54:09]
feature_dim: 32 [12/07 15:54:09]
D:\Project_3DGS\4DGaussians\data\multipleview\inputimage\cam103\frame_00001.jpg [12/07 15:54:09]
Traceback (most recent call last):
  File "D:\Project_3DGS\4DGaussians\train.py", line 429, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "D:\Project_3DGS\4DGaussians\train.py", line 303, in training
    scene = Scene(dataset, gaussians, load_coarse=None)
  File "D:\Project_3DGS\4DGaussians\scene\__init__.py", line 62, in __init__
    scene_info = sceneLoadTypeCallbacks["MultipleView"](args.source_path)
  File "D:\Project_3DGS\4DGaussians\scene\dataset_readers.py", line 605, in readMultipleViewinfos
    test_cam_infos = multipleview_dataset(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics, cam_folder=datadir,split="test")
  File "D:\Project_3DGS\4DGaussians\scene\multipleview_dataset.py", line 30, in __init__
    self.video_cam_infos=self.get_video_cam_infos(cam_folder)
  File "D:\Project_3DGS\4DGaussians\scene\multipleview_dataset.py", line 72, in get_video_cam_infos
    image = Image.open(self.image_paths[0])
  File "D:\Anaconda\envs\S3Gaussian\lib\site-packages\PIL\Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Project_3DGS\\4DGaussians\\data\\multipleview\\inputimage\\cam103\\frame_00001.jpg'

Hi，i get a confuse problem about my custom multiview training , i get the error infomation like this.
However , i only have three cam as you can see in the picture , what this program want to get images in cam103 ，and how can i solve the problem ?
![屏幕截图 2024-07-12 161317](https://github.com/user-attachments/assets/5a2bfbde-e18a-46ad-b07d-6ca20869fddd)

**Comment by Hongyuan-Tao** [comment]
Have you correctly followed the readme document process to use colmap to calculate point clouds and poses?

**Comment by DeoooChen** [comment]
Hello! I also encounter this problem, have you solved it?
my problem can be seen that:

(Gaussians4D) PS E:\work\4DGaussians-master> python train.py -s  data/multipleview/steak --port 6017 --expname "multipleview/steak" --configs arguments/multipleview/default.py 
Optimizing 
Output folder: ./output/multipleview/steak [18/10 19:40:08]
Tensorboard not available: not logging progress [18/10 19:40:08]
feature_dim: 32 [18/10 19:40:08]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6300/6300 [00:00<00:00, 431442.30it/s]
Loading Training Cameras [18/10 19:40:09]
Loading Test Cameras [18/10 19:40:09]
Loading Video Cameras [18/10 19:40:09]
Deformation Net Set aabb [21.92314148 13.91623799 42.18507004] [-27.94252586 -19.99491882   6.99479675] [18/10 19:40:09]
Voxel Plane: set aabb= Parameter containing:
tensor([[ 21.9231,  13.9162,  42.1851],
        [-27.9425, -19.9949,   6.9948]]) [18/10 19:40:09]
Number of points at initialisation :  37227 [18/10 19:40:09]
Training progress:   0%|                                                                                                                                                                                   | 0/3000 [00:00<?, ?it/s]data loading done [18/10 19:40:09]
Training progress:   0%|▍                                                                                                                              | 10/3000 [01:01<5:05:15,  6.13s/it, Loss=0.1849639, psnr=11.03, point=37227]Traceback (most recent call last):
  File "E:\work\4DGaussians\train.py", line 429, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "E:\work\4DGaussians\train.py", line 305, in training
    scene_reconstruction(dataset, opt, hyper, pipe, testing_iterations, saving_iterations,
  File "E:\work\4DGaussians\train.py", line 149, in scene_reconstruction
    viewpoint_cams = next(loader)
  File "D:\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "D:\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\data\dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "D:\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 10.
Original Traceback (most recent call last):
  File "E:\work\4DGaussians\scene\dataset.py", line 24, in __getitem__
    image, w2c, time = self.dataset[index]
  File "E:\work\4DGaussians\scene\multipleview_dataset.py", line 91, in __getitem__
    img = Image.open(self.image_paths[index])
  File "D:\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\PIL\Image.py", line 3493, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\work\\4DGaussians\\data\\multipleview\\steak\\cam21\\frame_00273.jpg'

During handling of the above exception, another exception occurred:
...
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\work\\4DGaussians\\data\\multipleview\\steak\\cam21\\frame_00273.jpg'


my folders in "./data/multipleview/steak/" are like:
|-cam00
|     |---frame_00001.jpg
|     |---...
|     |---frame_00300.jpg
|-cam01
|-...
|-cam20
|-sparse_
|-points3D_multipleviews.ply
|-poses_bounds_multipleview.npy

BUT I do not have 'cam21', what should I do?

**Comment by liumanfang** [comment]
> 你好！ 我也遇到了这个问题，你解决了吗？我的问题可以看出：
> 
> （高斯人4D）PS E：\work\4DGaussians-master> python train.py -s data/multipleview/steak --port 6017 --expname “multipleview/steak” --configs arguments/multipleview/default.py Optimizing Output folder： ./output/multipleview/steak [18/10 19：40：08] Tensorboard not avail能：未记录进度 [18/10 19：40：08] feature_dim： 32 [18/10 19：40：08] 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|6300/6300 [00：00<00：00， 431442.30it/s] 加载训练摄像头 [18/10 19：40：09] 加载测试摄像头 [18/10 19：40：09] 加载视频摄像头 [18/10 19：40：09] 变形网集合 aabb [21.92314148 13.91623799 42.18507004] [-27.94252586 -19.99491882 6.99479675] [18/10 19：40：09] 体素平面：set aabb= 包含：张量的参数（[[ 21.9231， 13.9162， 42.1851]， [-27.9425， -19.9949， 6.9948]]） [18/10 19：40：09] 初始化点数：37227 [18/10 19：40：09] 训练进度：0%| |0/3000 [00：00<?, ?it/s]数据加载完成 [18/10 19：40：09] 训练进度：0%|▍ |10/3000 [01：01<5：05：15， 6.13s/it， Loss=0.1849639， psnr=11.03， point=37227]Traceback（最近一次呼叫）：文件“E：\work\4DGaussians\train.py”，第429行，in training（lp.extract（args）， hp.extract（args）， op.extract（args）， pp.extract（args）， args.test_iterations， args.save_iterations， args.checkpoint_iterations， args.start_checkpoint， args.debug_from， args.expname） 文件 “E：\work\4DGaussians\train.py”，第305行，in training scene_reconstruction（dataset， opt， hyper， pipe， testing_iterations， saving_iterations，文件 “E：\work\4DGaussians\train.py”，第149行，scene_reconstruction viewpoint_cams = next（loader） 文件 “D：\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\data\dataloader.py“，第630行，**下一**条数据=self._next_data（）文件”D：\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\data\dataloader.py“，第1325行，_next_data返回self._process_data（data） 文件”D：\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\data\dataloader.py“，第1371行，_process_data data.reraise（） 文件 ”D：\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch_utils.py“，第694行，在 reraise raise exception FileNotFoundError： 在 DataLoader 工作进程 10 中捕获了 FileNotFoundError。原始回溯（最近一次调用）：文件“E：\work\4DGaussians\scene\dataset.py”，第24行，**getitem** image，w2c，时间 = self.dataset[index] 文件“E：\work\4DGaussians\scene\multipleview_dataset.py”，第91行，**getitem** img = Image.open（self.image_paths[index]） 文件 “D：\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\PIL\Image.py”，第 3493 行，打开中 fp = builtins.open（文件名，“rb”） FileNotFoundError： [Errno 2] 无此文件或目录： 'E：\work\4DGaussians\data\multipleview\steak\cam21\frame_00273.jpg'
> 
> 在处理上述异常时，又出现了另一个异常：...FileNotFoundError： [Errno 2] 没有这样的文件或目录：'E：\work\4DGaussians\data\multipleview\steak\cam21\frame_00273.jpg'
> 
> 我在“./data/multipleview/steak/”里的文件夹是这样的：|-cam00 | |---frame_00001.jpg | |---...| |---frame_00300.jpg |-cam01 |-...|-cam20 |-sparse_ |-points3D_multipleviews.ply |-poses_bounds_multipleview.npy
> 
> 但我没有“cam21”，我该怎么办？

Hello, have you resolved this issue? I'm encountering the same problem and would like to understand the cause and solution. Thank you for your reply.

**Comment by DeoooChen** [comment]
> > 你好！ 我也遇到了这个问题，你解决了吗？我的问题可以看出：
> > （高斯人4D）PS E：\work\4DGaussians-master> python train.py -s data/multipleview/steak --port 6017 --expname “multipleview/steak” --configs arguments/multipleview/default.py Optimizing Output folder： ./output/multipleview/steak [18/10 19：40：08] Tensorboard not avail能：未记录进度 [18/10 19：40：08] feature_dim： 32 [18/10 19：40：08] 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|6300/6300 [00：00<00：00， 431442.30it/s] 加载训练摄像头 [18/10 19：40：09] 加载测试摄像头 [18/10 19：40：09] 加载视频摄像头 [18/10 19：40：09] 变形网集合 aabb [21.92314148 13.91623799 42.18507004] [-27.94252586 -19.99491882 6.99479675] [18/10 19：40：09] 体素平面：set aabb= 包含：张量的参数（[[ 21.9231， 13.9162， 42.1851]， [-27.9425， -19.9949， 6.9948]]） [18/10 19：40：09] 初始化点数：37227 [18/10 19：40：09] 训练进度：0%| |0/3000 [00：00<?, ?it/s]数据加载完成 [18/10 19：40：09] 训练进度：0%|▍ |10/3000 [01：01<5：05：15， 6.13s/it， Loss=0.1849639， psnr=11.03， point=37227]Traceback（最近一次呼叫）：文件“E：\work\4DGaussians\train.py”，第429行，in training（lp.extract（args）， hp.extract（args）， op.extract（args）， pp.extract（args）， args.test_iterations， args.save_iterations， args.checkpoint_iterations， args.start_checkpoint， args.debug_from， args.expname） 文件 “E：\work\4DGaussians\train.py”，第305行，in training scene_reconstruction（dataset， opt， hyper， pipe， testing_iterations， saving_iterations，文件 “E：\work\4DGaussians\train.py”，第149行，scene_reconstruction viewpoint_cams = next（loader） 文件 “D：\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\data\dataloader.py“，第630行，**下一**条数据=self._next_data（）文件”D：\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\data\dataloader.py“，第1325行，_next_data返回self._process_data（data） 文件”D：\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\data\dataloader.py“，第1371行，_process_data data.reraise（） 文件 ”D：\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\torch_utils.py“，第694行，在 reraise raise exception FileNotFoundError： 在 DataLoader 工作进程 10 中捕获了 FileNotFoundError。原始回溯（最近一次调用）：文件“E：\work\4DGaussians\scene\dataset.py”，第24行，**getitem** image，w2c，时间 = self.dataset[index] 文件“E：\work\4DGaussians\scene\multipleview_dataset.py”，第91行，**getitem** img = Image.open（self.image_paths[index]） 文件 “D：\LEN\Anaconda3\envs\Gaussians4D\lib\site-packages\PIL\Image.py”，第 3493 行，打开中 fp = builtins.open（文件名，“rb”） FileNotFoundError： [Errno 2] 无此文件或目录： 'E：\work\4DGaussians\data\multipleview\steak\cam21\frame_00273.jpg'
> > 在处理上述异常时，又出现了另一个异常：...FileNotFoundError： [Errno 2] 没有这样的文件或目录：'E：\work\4DGaussians\data\multipleview\steak\cam21\frame_00273.jpg'
> > 我在“./data/multipleview/steak/”里的文件夹是这样的：|-cam00 | |---frame_00001.jpg | |---...| |---frame_00300.jpg |-cam01 |-...|-cam20 |-sparse_ |-points3D_multipleviews.ply |-poses_bounds_multipleview.npy
> > 但我没有“cam21”，我该怎么办？
> 
> Hello, have you resolved this issue? I'm encountering the same problem and would like to understand the cause and solution. Thank you for your reply.

可以看一下是否有类似于.ipynb_checkpoints的隐藏文件夹，删掉就可以了
