### ISSUE TITLE
Training error on cook_spinach

### ISSUE THREAD

**Issue by lulinliu** [hustvl/4DGaussians#170]
Thank you for your work. 

when I try to enter this command: python train.py -s data/dynerf/cook_spinach --port 6017 --expname "dynerf/cook_spinach" --configs arguments/dynerf/cook_spinach.py 

The terminal shows that 
Optimizing 
Output folder: ./output/dynerf/cook_spinach [19/07 09:39:41]
Tensorboard not available: not logging progress [19/07 09:39:41]
feature_dim: 32 [19/07 09:39:41]
Traceback (most recent call last):
  File "train.py", line 429, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "train.py", line 303, in training
    scene = Scene(dataset, gaussians, load_coarse=None)
  File "/home/lulin/PycharmProjects/4DGaussians/scene/__init__.py", line 53, in __init__
    scene_info = sceneLoadTypeCallbacks["dynerf"](args.source_path, args.white_background, args.eval)
  File "/home/lulin/PycharmProjects/4DGaussians/scene/dataset_readers.py", line 453, in readdynerfInfo
    eval_index=0,
  File "/home/lulin/PycharmProjects/4DGaussians/scene/neural_3D_dataset_NDC.py", line 254, in __init__
    self.load_meta()
  File "/home/lulin/PycharmProjects/4DGaussians/scene/neural_3D_dataset_NDC.py", line 269, in load_meta
    assert len(videos) == poses_arr.shape[0]
AssertionError

Can anyone help me to fix this issue? Thank you.

**Comment by lulinliu** [comment]
Follow up:

I just figure it out.

That's because I delete all original video so that the len(video)=0

**Comment by ihuchao** [comment]
Thanks!
