### ISSUE TITLE
No good initial image pair found. (multipleviewprogress.sh)

### ISSUE THREAD

**Issue by MaryneZa** [hustvl/4DGaussians#200]
command : bash multiviewprogresss.sh dataset-name

I have run the above command and i got this LOG

```
I1028 12:01:55.911984 501025 incremental_mapper.cc:286] Finding good initial image pair
I1028 12:24:31.008410 501025 incremental_mapper.cc:290] => No good initial image pair found.
I1028 12:24:31.059327 501025 incremental_mapper.cc:286] Finding good initial image pair
I1028 12:24:34.454192 501025 incremental_mapper.cc:290] => No good initial image pair found.
```
<img width="176" alt="Screenshot 2024-10-28 113115" src="https://github.com/user-attachments/assets/8f0133b0-f0ea-4af6-b94b-87e6294c82c4">

(image total of cam01 and cam02 is 330)

<img width="703" alt="Screenshot 2024-10-28 113331" src="https://github.com/user-attachments/assets/b9571707-162b-4d82-9221-44cb12383f26">
<img width="704" alt="Screenshot 2024-10-28 113306" src="https://github.com/user-attachments/assets/8797e1dc-c880-4265-b50a-7d7a0af546d5">

(image "sample" frame_00050.jpg of both cam)

I have no idea where I have to fix , I dont know does it because of my image input is not suit enough, can you guide me plz 😿

**Comment by guanjunwu** [comment]
Only 2 cams? it indeen hard to generate the point by COLMAP...
maybe more than 5 cams can work(I guess)
or you can use DUST3R to generate init point clouds and poses.

**Comment by MaryneZa** [comment]
> Only 2 cams? it indeen hard to generate the point by COLMAP... maybe more than 5 cams can work(I guess) or you can use DUST3R to generate init point clouds and poses.

Thanks for helping !
I have a question ... does all of the cam have to capture movement in the same time ? I mean same time but difference view

**Comment by MaryneZa** [comment]
> Only 2 cams? it indeen hard to generate the point by COLMAP... maybe more than 5 cams can work(I guess) or you can use DUST3R to generate init point clouds and poses.

<img width="136" alt="Screenshot 2024-10-28 140244" src="https://github.com/user-attachments/assets/e3752d72-0e3b-4216-a6e5-179a65249ac6">

I have used 10 cam but I still got the same message .. TT

**Comment by MaryneZa** [comment]
> Only 2 cams? it indeen hard to generate the point by COLMAP... maybe more than 5 cams can work(I guess) or you can use DUST3R to generate init point clouds and poses.

I have try 30 cam and its work properly till I found the next problem ...

`==============================================================================                                              
Feature extraction                                                                                                          
==============================================================================                                              
I1028 16:00:02.641295 533364 sift.cc:721] Creating SIFT GPU feature extractor                                               
I1028 16:00:02.642710 533331 timer.cc:91] Elapsed time: 0.000 [minutes]                                                     
Features extracted                                                                                                          
I1028 16:00:02.682385 533368 misc.cc:44]                                                                                    
==============================================================================                                              
Feature matching                                                                                                            
==============================================================================                                              
I1028 16:00:02.682652 533369 sift.cc:1426] Creating SIFT GPU feature matcher
E1028 16:00:02.682696 533369 logging.h:126] [sift.cc:89] Check failed: max_num_matches > 0 (0 vs. 0)
E1028 16:00:02.682709 533369 sift.cc:1174] Check failed: options_.Check() 
terminate called after throwing an instance of 'std::invalid_argument'
what():  [sift.cc:1174] Check failed: options_.Check() 
*** Aborted at 1730102402 (unix time) try "date -d @1730102402" if you are using GNU date ***
PC: @     0x7fc52de4e00b gsignal
*** SIGABRT (@0x3e800082376) received by PID 533366 (TID 0x7fc525711000) from PID 533366; stack trace: ***
    @     0x7fc52f657631 (unknown)
    @     0x7fc52f62e420 (unknown)
    @     0x7fc52de4e00b gsignal
    @     0x7fc52de2d859 abort
    @     0x7fc52e2078d1 (unknown)
    @     0x7fc52e21337c (unknown)
    @     0x7fc52e2133e7 std::terminate()
    @     0x7fc52e213699 __cxa_throw
    @     0x562c5d550eca colmap::LogMessageFatalThrow<>::~LogMessageFatalThrow()
    @     0x562c5db521fb colmap::(anonymous namespace)::SiftGPUFeatureMatcher::Create()
    @     0x562c5db523e9 colmap::CreateSiftFeatureMatcher()
    @     0x562c5d602fe8 colmap::FeatureMatcherWorker::Run()
    @     0x562c5d6b4cf1 colmap::Thread::RunFunc()
    @     0x7fc52e23fdf4 (unknown)
    @     0x7fc52f622609 start_thread
    @     0x7fc52df2a353 clone
Traceback (most recent call last):
  File "LLFF/imgs2poses.py", line 18, in <module>
  gen_poses(args.scenedir, args.match_type)
  File "/home/mare-4d/work/4DGaussians/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/home/mare-4d/work/4DGaussians/LLFF/llff/poses/colmap_wrapper.py", line 44, in run_colmap
    match_output = ( subprocess.check_output(exhaustive_matcher_args, universal_newlines=True) )
  File "/home/mare-4d/miniconda3/envs/Gaussians4D/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/mare-4d/miniconda3/envs/Gaussians4D/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['colmap', 'exhaustive_matcher', '--database_path', './colmap_tmp/database.db']' die
d with <Signals.SIGABRT: 6>.
cp: cannot stat './colmap_tmp/poses_bounds.npy': No such file or directory`

**Comment by MaryneZa** [comment]
> > Only 2 cams? it indeen hard to generate the point by COLMAP... maybe more than 5 cams can work(I guess) or you can use DUST3R to generate init point clouds and poses.
> 
> I have try 30 cam and its work properly till I found the next problem ...
> 
> ```
> ==============================================================================                                              
> Feature extraction                                                                                                          
> ==============================================================================                                              
> I1028 16:00:02.641295 533364 sift.cc:721] Creating SIFT GPU feature extractor                                               
> I1028 16:00:02.642710 533331 timer.cc:91] Elapsed time: 0.000 [minutes]                                                     
> Features extracted                                                                                                          
> I1028 16:00:02.682385 533368 misc.cc:44]                                                                                    
> ==============================================================================                                              
> Feature matching                                                                                                            
> ==============================================================================                                              
> I1028 16:00:02.682652 533369 sift.cc:1426] Creating SIFT GPU feature matcher
> E1028 16:00:02.682696 533369 logging.h:126] [sift.cc:89] Check failed: max_num_matches > 0 (0 vs. 0)
> E1028 16:00:02.682709 533369 sift.cc:1174] Check failed: options_.Check() 
> terminate called after throwing an instance of 'std::invalid_argument'
> what():  [sift.cc:1174] Check failed: options_.Check() 
> *** Aborted at 1730102402 (unix time) try "date -d @1730102402" if you are using GNU date ***
> PC: @     0x7fc52de4e00b gsignal
> *** SIGABRT (@0x3e800082376) received by PID 533366 (TID 0x7fc525711000) from PID 533366; stack trace: ***
>     @     0x7fc52f657631 (unknown)
>     @     0x7fc52f62e420 (unknown)
>     @     0x7fc52de4e00b gsignal
>     @     0x7fc52de2d859 abort
>     @     0x7fc52e2078d1 (unknown)
>     @     0x7fc52e21337c (unknown)
>     @     0x7fc52e2133e7 std::terminate()
>     @     0x7fc52e213699 __cxa_throw
>     @     0x562c5d550eca colmap::LogMessageFatalThrow<>::~LogMessageFatalThrow()
>     @     0x562c5db521fb colmap::(anonymous namespace)::SiftGPUFeatureMatcher::Create()
>     @     0x562c5db523e9 colmap::CreateSiftFeatureMatcher()
>     @     0x562c5d602fe8 colmap::FeatureMatcherWorker::Run()
>     @     0x562c5d6b4cf1 colmap::Thread::RunFunc()
>     @     0x7fc52e23fdf4 (unknown)
>     @     0x7fc52f622609 start_thread
>     @     0x7fc52df2a353 clone
> Traceback (most recent call last):
>   File "LLFF/imgs2poses.py", line 18, in <module>
>   gen_poses(args.scenedir, args.match_type)
>   File "/home/mare-4d/work/4DGaussians/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
>     run_colmap(basedir, match_type)
>   File "/home/mare-4d/work/4DGaussians/LLFF/llff/poses/colmap_wrapper.py", line 44, in run_colmap
>     match_output = ( subprocess.check_output(exhaustive_matcher_args, universal_newlines=True) )
>   File "/home/mare-4d/miniconda3/envs/Gaussians4D/lib/python3.7/subprocess.py", line 411, in check_output
>     **kwargs).stdout
>   File "/home/mare-4d/miniconda3/envs/Gaussians4D/lib/python3.7/subprocess.py", line 512, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['colmap', 'exhaustive_matcher', '--database_path', './colmap_tmp/database.db']' die
> d with <Signals.SIGABRT: 6>.
> cp: cannot stat './colmap_tmp/poses_bounds.npy': No such file or directory
> ```

the problemis solved ! there is the problem with 
`git clone https://github.com/Fyusion/LLFF.git #multipleviewprogress.py` 
the installation did not work properly.

**Comment by guanjunwu** [comment]
yes, maybe you should write a script to align them.

**Comment by liuhaixu2021** [comment]
I'd like to ask about some details of writing this script, such as what the data structure is within the bins output by colmap.
