### ISSUE TITLE
Training on data exported from Metashape

### ISSUE THREAD

**Issue by ariannaferraris** [hustvl/4DGaussians#221]
Hi there,

Firstly, thank you for your work!

I was trying to train the model on COLMAP data extracted from Metashape, that I managed to obtain through this script https://github.com/agisoft-llc/metashape-scripts/blob/master/src/export_for_gaussian_splatting.py

The folder structure I get after exporting my data from Metashape is the following:

- frame_000001

  -  images
     - cam01_frame_000001
     - cam02_frame_000001
     - cam03_frame_000001
     - …
  - sparse
     - 0
        - cameras.bin
        - images.bin
        - points3D.bin
- frame_000002

  -  images
     - cam01_frame_000002
     - cam02_frame_000002
     - cam03_frame_000002
     - …
  - sparse
     - 0
        - cameras.bin
        - images.bin
        - points3D.bin
-  …

However, as soon as I try to train using the command  python train.py -s {filedir} --port 6017 --expname "GS0003_Arianna_test" --configs arguments/hypernerf/default.py  I get the following error:

Traceback (most recent call last):
  File "train.py", line 428, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "train.py", line 302, in training
    scene = Scene(dataset, gaussians, load_coarse=None)
  File "...\4DGaussians\scene\__init__.py", line 65, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

I also tried without --configs arguments/hypernerf/default.py but I get the same error.

Could someone help me in understanding what’s wrong? If I try to train one single frame, I don’t have any problems and the result looks great, but now that I wanted to add the time dimension I cannot make it work. My setup consists of 42 static cameras and I was trying to train on 40 frames in total. 

Thank you in advance!

**Comment by shoang22** [comment]
Hi, were you able to resolve this?
