### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'V:\\github_projects\\4DGausssian\\4DGaussians\\data\\hypernerf\\interp_chickchicken\\chickchicken\\points3D_downsample.ply'

### ISSUE THREAD

**Issue by GYH-skywalker** [hustvl/4DGaussians#91]
when i training with hypernerf dataset i got this error
```
Traceback (most recent call last):
  File "V:\github_projects\4DGausssian\4DGaussians\train.py", line 429, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "V:\github_projects\4DGausssian\4DGaussians\train.py", line 303, in training
    scene = Scene(dataset, gaussians, load_coarse=None)
  File "V:\github_projects\4DGausssian\4DGaussians\scene\__init__.py", line 56, in __init__
    scene_info = sceneLoadTypeCallbacks["nerfies"](args.source_path, False, args.eval)
  File "V:\github_projects\4DGausssian\4DGaussians\scene\dataset_readers.py", line 386, in readHyperDataInfos
    pcd = fetchPly(ply_path)
  File "V:\github_projects\4DGausssian\4DGaussians\scene\dataset_readers.py", line 125, in fetchPly
    plydata = PlyData.read(path)
  File "D:\Anaconda\envs\Gaussians4D\lib\site-packages\plyfile.py", line 158, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File "D:\Anaconda\envs\Gaussians4D\lib\site-packages\plyfile.py", line 1345, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: 'V:\\github_projects\\4DGausssian\\4DGaussians\\data\\hypernerf\\interp_chickchicken\\chickchicken\\points3D_downsample.ply'
```
I've checked this dir "V:\\github_projects\\4DGausssian\\4DGaussians\\data\\hypernerf\\interp_chickchicken\\chickchicken\\",and there is not points3D_downsample.ply even though i executed `colmap.sh`
this is my hypernerf dataset directory tree:
![image](https://github.com/hustvl/4DGaussians/assets/91406396/77bb5d09-cd76-437d-8e43-3e4dd17c60c5)

**Comment by guanjunwu** [comment]
you should downsample point  by `downsample_point.py `
